"""add trades table

Revision ID: 19fd7ee6e5a2
Revises: b6a218f6648d
Create Date: 2026-07-09 23:38:07.208592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19fd7ee6e5a2'
down_revision: Union[str, None] = 'b6a218f6648d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trades',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('dedup', sa.String(length=128), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('maker_order_id', sa.Integer(), nullable=False),
    sa.Column('taker_order_id', sa.Integer(), nullable=False),
    sa.Column('aggressor_side', sa.String(length=8), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['maker_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['taker_order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup')
    )
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_table('trades')
    # ### end Alembic commands ###
